/*
 * Hornet API
 *
 * The Hornet API can be used to programmatically update exposed association data. If you're missing functionality or you experience any problem using the API, you can always contact us.  You will need an API token consisting of a client id and a token value in order to use this API. You can either authenticate using a request header or a query parameter, the choice is yours.  The API is only documented in English.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{Error, configuration};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use std::sync::Arc;

#[async_trait]
pub trait AssociationApi: Send + Sync {
    /// DELETE /api/association/members/{associationMemberId}
    ///
    ///
    async fn delete_app_apicontrollers_associationapi_deletemember(
        &self,
        params: DeleteAppApicontrollersAssociationapiDeletememberParams,
    ) -> Result<
        models::DeleteAppApicontrollersAssociationapiDeletemember200Response,
        Error<DeleteAppApicontrollersAssociationapiDeletememberError>,
    >;

    /// GET /api/association
    ///
    ///
    async fn get_app_apicontrollers_associationapi_get(
        &self,
    ) -> Result<models::Association, Error<GetAppApicontrollersAssociationapiGetError>>;

    /// GET /api/association/members/{associationMemberId}
    ///
    ///
    async fn get_app_apicontrollers_associationapi_getmember(
        &self,
        params: GetAppApicontrollersAssociationapiGetmemberParams,
    ) -> Result<models::AssociationMember, Error<GetAppApicontrollersAssociationapiGetmemberError>>;

    /// GET /api/association/members
    ///
    ///
    async fn get_app_apicontrollers_associationapi_getmembers(
        &self,
    ) -> Result<
        Vec<models::AssociationMember>,
        Error<GetAppApicontrollersAssociationapiGetmembersError>,
    >;

    /// POST /api/association/members
    ///
    ///
    async fn post_app_apicontrollers_associationapi_postmember(
        &self,
        params: PostAppApicontrollersAssociationapiPostmemberParams,
    ) -> Result<models::AssociationMember, Error<PostAppApicontrollersAssociationapiPostmemberError>>;

    /// PUT /api/association
    ///
    ///
    async fn put_app_apicontrollers_associationapi_put(
        &self,
        params: PutAppApicontrollersAssociationapiPutParams,
    ) -> Result<models::Association, Error<PutAppApicontrollersAssociationapiPutError>>;

    /// PUT /api/association/members/{associationMemberId}
    ///
    ///
    async fn put_app_apicontrollers_associationapi_putmember(
        &self,
        params: PutAppApicontrollersAssociationapiPutmemberParams,
    ) -> Result<models::AssociationMember, Error<PutAppApicontrollersAssociationapiPutmemberError>>;
}

pub struct AssociationApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl AssociationApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`AssociationApi::delete_app_apicontrollers_associationapi_deletemember`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteAppApicontrollersAssociationapiDeletememberParams {
    /// Association member ID
    pub association_member_id: i32,
}

/// struct for passing parameters to the method [`AssociationApi::get_app_apicontrollers_associationapi_getmember`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetAppApicontrollersAssociationapiGetmemberParams {
    /// Association member ID
    pub association_member_id: i32,
}

/// struct for passing parameters to the method [`AssociationApi::post_app_apicontrollers_associationapi_postmember`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct PostAppApicontrollersAssociationapiPostmemberParams {
    pub create_association_member: Option<models::CreateAssociationMember>,
}

/// struct for passing parameters to the method [`AssociationApi::put_app_apicontrollers_associationapi_put`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct PutAppApicontrollersAssociationapiPutParams {
    pub update_association: Option<models::UpdateAssociation>,
}

/// struct for passing parameters to the method [`AssociationApi::put_app_apicontrollers_associationapi_putmember`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct PutAppApicontrollersAssociationapiPutmemberParams {
    /// Association member ID
    pub association_member_id: i32,
    pub update_association_member: Option<models::UpdateAssociationMember>,
}

#[async_trait]
impl AssociationApi for AssociationApiClient {
    async fn delete_app_apicontrollers_associationapi_deletemember(
        &self,
        params: DeleteAppApicontrollersAssociationapiDeletememberParams,
    ) -> Result<
        models::DeleteAppApicontrollersAssociationapiDeletemember200Response,
        Error<DeleteAppApicontrollersAssociationapiDeletememberError>,
    > {
        let DeleteAppApicontrollersAssociationapiDeletememberParams {
            association_member_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/association/members/{associationMemberId}",
            local_var_configuration.base_path,
            associationMemberId = association_member_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::DeleteAppApicontrollersAssociationapiDeletemember200Response`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DeleteAppApicontrollersAssociationapiDeletemember200Response`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<DeleteAppApicontrollersAssociationapiDeletememberError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_app_apicontrollers_associationapi_get(
        &self,
    ) -> Result<models::Association, Error<GetAppApicontrollersAssociationapiGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/association", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Association`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Association`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetAppApicontrollersAssociationapiGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_app_apicontrollers_associationapi_getmember(
        &self,
        params: GetAppApicontrollersAssociationapiGetmemberParams,
    ) -> Result<models::AssociationMember, Error<GetAppApicontrollersAssociationapiGetmemberError>>
    {
        let GetAppApicontrollersAssociationapiGetmemberParams {
            association_member_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/association/members/{associationMemberId}",
            local_var_configuration.base_path,
            associationMemberId = association_member_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::AssociationMember`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AssociationMember`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetAppApicontrollersAssociationapiGetmemberError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_app_apicontrollers_associationapi_getmembers(
        &self,
    ) -> Result<
        Vec<models::AssociationMember>,
        Error<GetAppApicontrollersAssociationapiGetmembersError>,
    > {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/association/members",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::AssociationMember&gt;`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `Vec&lt;models::AssociationMember&gt;`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetAppApicontrollersAssociationapiGetmembersError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn post_app_apicontrollers_associationapi_postmember(
        &self,
        params: PostAppApicontrollersAssociationapiPostmemberParams,
    ) -> Result<models::AssociationMember, Error<PostAppApicontrollersAssociationapiPostmemberError>>
    {
        let PostAppApicontrollersAssociationapiPostmemberParams {
            create_association_member,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/association/members",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&create_association_member);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::AssociationMember`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AssociationMember`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<PostAppApicontrollersAssociationapiPostmemberError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn put_app_apicontrollers_associationapi_put(
        &self,
        params: PutAppApicontrollersAssociationapiPutParams,
    ) -> Result<models::Association, Error<PutAppApicontrollersAssociationapiPutError>> {
        let PutAppApicontrollersAssociationapiPutParams { update_association } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/association", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&update_association);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Association`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Association`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<PutAppApicontrollersAssociationapiPutError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn put_app_apicontrollers_associationapi_putmember(
        &self,
        params: PutAppApicontrollersAssociationapiPutmemberParams,
    ) -> Result<models::AssociationMember, Error<PutAppApicontrollersAssociationapiPutmemberError>>
    {
        let PutAppApicontrollersAssociationapiPutmemberParams {
            association_member_id,
            update_association_member,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/association/members/{associationMemberId}",
            local_var_configuration.base_path,
            associationMemberId = association_member_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&update_association_member);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::AssociationMember`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AssociationMember`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<PutAppApicontrollersAssociationapiPutmemberError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`AssociationApi::delete_app_apicontrollers_associationapi_deletemember`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAppApicontrollersAssociationapiDeletememberError {
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AssociationApi::get_app_apicontrollers_associationapi_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAppApicontrollersAssociationapiGetError {
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AssociationApi::get_app_apicontrollers_associationapi_getmember`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAppApicontrollersAssociationapiGetmemberError {
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AssociationApi::get_app_apicontrollers_associationapi_getmembers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAppApicontrollersAssociationapiGetmembersError {
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AssociationApi::post_app_apicontrollers_associationapi_postmember`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostAppApicontrollersAssociationapiPostmemberError {
    Status400(models::PutAppApicontrollersAssociationapiPut400Response),
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AssociationApi::put_app_apicontrollers_associationapi_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutAppApicontrollersAssociationapiPutError {
    Status400(models::PutAppApicontrollersAssociationapiPut400Response),
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AssociationApi::put_app_apicontrollers_associationapi_putmember`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutAppApicontrollersAssociationapiPutmemberError {
    Status400(models::PutAppApicontrollersAssociationapiPut400Response),
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}
