/*
 * Hornet API
 *
 * The Hornet API can be used to programmatically update exposed association data. If you're missing functionality or you experience any problem using the API, you can always contact us.  You will need an API token consisting of a client id and a token value in order to use this API. You can either authenticate using a request header or a query parameter, the choice is yours.  The API is only documented in English.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{Error, configuration};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{Deserialize, Serialize, de::Error as _};
use std::sync::Arc;

#[async_trait]
pub trait GroupApi: Send + Sync {
    /// DELETE /api/group/{groupId}
    ///
    ///
    async fn delete_app_apicontrollers_committeeapi_deletecommittee(
        &self,
        params: DeleteAppApicontrollersCommitteeapiDeletecommitteeParams,
    ) -> Result<
        models::DeleteAppApicontrollersAssociationapiDeletemember200Response,
        Error<DeleteAppApicontrollersCommitteeapiDeletecommitteeError>,
    >;

    /// DELETE /api/group/{groupId}/members/{groupMemberId}
    ///
    ///
    async fn delete_app_apicontrollers_committeeapi_deletemember(
        &self,
        params: DeleteAppApicontrollersCommitteeapiDeletememberParams,
    ) -> Result<
        models::DeleteAppApicontrollersAssociationapiDeletemember200Response,
        Error<DeleteAppApicontrollersCommitteeapiDeletememberError>,
    >;

    /// GET /api/group
    ///
    ///
    async fn get_app_apicontrollers_committeeapi_get(
        &self,
    ) -> Result<Vec<models::Group>, Error<GetAppApicontrollersCommitteeapiGetError>>;

    /// GET /api/group/{groupId}
    ///
    ///
    async fn get_app_apicontrollers_committeeapi_getcommittee(
        &self,
        params: GetAppApicontrollersCommitteeapiGetcommitteeParams,
    ) -> Result<models::Group, Error<GetAppApicontrollersCommitteeapiGetcommitteeError>>;

    /// GET /api/group/{groupId}/members/{groupMemberId}
    ///
    ///
    async fn get_app_apicontrollers_committeeapi_getmember(
        &self,
        params: GetAppApicontrollersCommitteeapiGetmemberParams,
    ) -> Result<models::GroupMember, Error<GetAppApicontrollersCommitteeapiGetmemberError>>;

    /// GET /api/group/{groupId}/members
    ///
    ///
    async fn get_app_apicontrollers_committeeapi_getmembers(
        &self,
        params: GetAppApicontrollersCommitteeapiGetmembersParams,
    ) -> Result<Vec<models::GroupMember>, Error<GetAppApicontrollersCommitteeapiGetmembersError>>;

    /// POST /api/group
    ///
    ///
    async fn post_app_apicontrollers_committeeapi_postcommittee(
        &self,
        params: PostAppApicontrollersCommitteeapiPostcommitteeParams,
    ) -> Result<models::Group, Error<PostAppApicontrollersCommitteeapiPostcommitteeError>>;

    /// POST /api/group/{groupId}/members
    ///
    ///
    async fn post_app_apicontrollers_committeeapi_postmember(
        &self,
        params: PostAppApicontrollersCommitteeapiPostmemberParams,
    ) -> Result<models::GroupMember, Error<PostAppApicontrollersCommitteeapiPostmemberError>>;

    /// PUT /api/group/{groupId}
    ///
    ///
    async fn put_app_apicontrollers_committeeapi_putcommittee(
        &self,
        params: PutAppApicontrollersCommitteeapiPutcommitteeParams,
    ) -> Result<models::Group, Error<PutAppApicontrollersCommitteeapiPutcommitteeError>>;

    /// PUT /api/group/{groupId}/archive
    ///
    /// Note that when you disable an archive, all e-mails in it will be lost!
    async fn put_app_apicontrollers_committeeapi_putcommitteearchive(
        &self,
        params: PutAppApicontrollersCommitteeapiPutcommitteearchiveParams,
    ) -> Result<models::Group, Error<PutAppApicontrollersCommitteeapiPutcommitteearchiveError>>;
}

pub struct GroupApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl GroupApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`GroupApi::delete_app_apicontrollers_committeeapi_deletecommittee`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteAppApicontrollersCommitteeapiDeletecommitteeParams {
    /// Group ID
    pub group_id: i32,
}

/// struct for passing parameters to the method [`GroupApi::delete_app_apicontrollers_committeeapi_deletemember`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct DeleteAppApicontrollersCommitteeapiDeletememberParams {
    /// Group ID
    pub group_id: i32,
    /// Group member ID
    pub group_member_id: i32,
}

/// struct for passing parameters to the method [`GroupApi::get_app_apicontrollers_committeeapi_getcommittee`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetAppApicontrollersCommitteeapiGetcommitteeParams {
    /// Group ID
    pub group_id: i32,
}

/// struct for passing parameters to the method [`GroupApi::get_app_apicontrollers_committeeapi_getmember`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetAppApicontrollersCommitteeapiGetmemberParams {
    /// Group ID
    pub group_id: i32,
    /// Group member ID
    pub group_member_id: i32,
}

/// struct for passing parameters to the method [`GroupApi::get_app_apicontrollers_committeeapi_getmembers`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct GetAppApicontrollersCommitteeapiGetmembersParams {
    /// Group ID
    pub group_id: i32,
}

/// struct for passing parameters to the method [`GroupApi::post_app_apicontrollers_committeeapi_postcommittee`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct PostAppApicontrollersCommitteeapiPostcommitteeParams {
    pub create_group: Option<models::CreateGroup>,
}

/// struct for passing parameters to the method [`GroupApi::post_app_apicontrollers_committeeapi_postmember`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct PostAppApicontrollersCommitteeapiPostmemberParams {
    /// Group ID
    pub group_id: i32,
    pub new_group_member: Option<models::NewGroupMember>,
}

/// struct for passing parameters to the method [`GroupApi::put_app_apicontrollers_committeeapi_putcommittee`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct PutAppApicontrollersCommitteeapiPutcommitteeParams {
    /// Group ID
    pub group_id: i32,
    pub update_group: Option<models::UpdateGroup>,
}

/// struct for passing parameters to the method [`GroupApi::put_app_apicontrollers_committeeapi_putcommitteearchive`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder))]
pub struct PutAppApicontrollersCommitteeapiPutcommitteearchiveParams {
    /// Group ID
    pub group_id: i32,
    pub update_group_archive: Option<models::UpdateGroupArchive>,
}

#[async_trait]
impl GroupApi for GroupApiClient {
    async fn delete_app_apicontrollers_committeeapi_deletecommittee(
        &self,
        params: DeleteAppApicontrollersCommitteeapiDeletecommitteeParams,
    ) -> Result<
        models::DeleteAppApicontrollersAssociationapiDeletemember200Response,
        Error<DeleteAppApicontrollersCommitteeapiDeletecommitteeError>,
    > {
        let DeleteAppApicontrollersCommitteeapiDeletecommitteeParams { group_id } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/group/{groupId}",
            local_var_configuration.base_path,
            groupId = group_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::DeleteAppApicontrollersAssociationapiDeletemember200Response`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DeleteAppApicontrollersAssociationapiDeletemember200Response`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<DeleteAppApicontrollersCommitteeapiDeletecommitteeError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn delete_app_apicontrollers_committeeapi_deletemember(
        &self,
        params: DeleteAppApicontrollersCommitteeapiDeletememberParams,
    ) -> Result<
        models::DeleteAppApicontrollersAssociationapiDeletemember200Response,
        Error<DeleteAppApicontrollersCommitteeapiDeletememberError>,
    > {
        let DeleteAppApicontrollersCommitteeapiDeletememberParams {
            group_id,
            group_member_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/group/{groupId}/members/{groupMemberId}",
            local_var_configuration.base_path,
            groupId = group_id,
            groupMemberId = group_member_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::DeleteAppApicontrollersAssociationapiDeletemember200Response`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::DeleteAppApicontrollersAssociationapiDeletemember200Response`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<DeleteAppApicontrollersCommitteeapiDeletememberError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_app_apicontrollers_committeeapi_get(
        &self,
    ) -> Result<Vec<models::Group>, Error<GetAppApicontrollersCommitteeapiGetError>> {
        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/group", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::Group&gt;`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `Vec&lt;models::Group&gt;`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetAppApicontrollersCommitteeapiGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_app_apicontrollers_committeeapi_getcommittee(
        &self,
        params: GetAppApicontrollersCommitteeapiGetcommitteeParams,
    ) -> Result<models::Group, Error<GetAppApicontrollersCommitteeapiGetcommitteeError>> {
        let GetAppApicontrollersCommitteeapiGetcommitteeParams { group_id } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/group/{groupId}",
            local_var_configuration.base_path,
            groupId = group_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Group`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Group`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetAppApicontrollersCommitteeapiGetcommitteeError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_app_apicontrollers_committeeapi_getmember(
        &self,
        params: GetAppApicontrollersCommitteeapiGetmemberParams,
    ) -> Result<models::GroupMember, Error<GetAppApicontrollersCommitteeapiGetmemberError>> {
        let GetAppApicontrollersCommitteeapiGetmemberParams {
            group_id,
            group_member_id,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/group/{groupId}/members/{groupMemberId}",
            local_var_configuration.base_path,
            groupId = group_id,
            groupMemberId = group_member_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::GroupMember`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::GroupMember`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetAppApicontrollersCommitteeapiGetmemberError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn get_app_apicontrollers_committeeapi_getmembers(
        &self,
        params: GetAppApicontrollersCommitteeapiGetmembersParams,
    ) -> Result<Vec<models::GroupMember>, Error<GetAppApicontrollersCommitteeapiGetmembersError>>
    {
        let GetAppApicontrollersCommitteeapiGetmembersParams { group_id } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/group/{groupId}/members",
            local_var_configuration.base_path,
            groupId = group_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `Vec&lt;models::GroupMember&gt;`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `Vec&lt;models::GroupMember&gt;`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<GetAppApicontrollersCommitteeapiGetmembersError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn post_app_apicontrollers_committeeapi_postcommittee(
        &self,
        params: PostAppApicontrollersCommitteeapiPostcommitteeParams,
    ) -> Result<models::Group, Error<PostAppApicontrollersCommitteeapiPostcommitteeError>> {
        let PostAppApicontrollersCommitteeapiPostcommitteeParams { create_group } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/group", local_var_configuration.base_path);
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&create_group);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Group`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Group`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<PostAppApicontrollersCommitteeapiPostcommitteeError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn post_app_apicontrollers_committeeapi_postmember(
        &self,
        params: PostAppApicontrollersCommitteeapiPostmemberParams,
    ) -> Result<models::GroupMember, Error<PostAppApicontrollersCommitteeapiPostmemberError>> {
        let PostAppApicontrollersCommitteeapiPostmemberParams {
            group_id,
            new_group_member,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/group/{groupId}/members",
            local_var_configuration.base_path,
            groupId = group_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&new_group_member);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::GroupMember`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::GroupMember`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<PostAppApicontrollersCommitteeapiPostmemberError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn put_app_apicontrollers_committeeapi_putcommittee(
        &self,
        params: PutAppApicontrollersCommitteeapiPutcommitteeParams,
    ) -> Result<models::Group, Error<PutAppApicontrollersCommitteeapiPutcommitteeError>> {
        let PutAppApicontrollersCommitteeapiPutcommitteeParams {
            group_id,
            update_group,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/group/{groupId}",
            local_var_configuration.base_path,
            groupId = group_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&update_group);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Group`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Group`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<PutAppApicontrollersCommitteeapiPutcommitteeError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Note that when you disable an archive, all e-mails in it will be lost!
    async fn put_app_apicontrollers_committeeapi_putcommitteearchive(
        &self,
        params: PutAppApicontrollersCommitteeapiPutcommitteearchiveParams,
    ) -> Result<models::Group, Error<PutAppApicontrollersCommitteeapiPutcommitteearchiveError>>
    {
        let PutAppApicontrollersCommitteeapiPutcommitteearchiveParams {
            group_id,
            update_group_archive,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/group/{groupId}/archive",
            local_var_configuration.base_path,
            groupId = group_id
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.query(&[("api-auth", local_var_value)]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        if let Some(ref local_var_apikey) = local_var_configuration.api_key {
            let local_var_key = local_var_apikey.key.clone();
            let local_var_value = match local_var_apikey.prefix {
                Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
                None => local_var_key,
            };
            local_var_req_builder = local_var_req_builder.header("X-API-AUTH", local_var_value);
        };
        local_var_req_builder = local_var_req_builder.json(&update_group_archive);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => {
                    return Err(Error::from(serde_json::Error::custom(
                        "Received `text/plain` content type response that cannot be converted to `models::Group`",
                    )));
                }
                ContentType::Unsupported(local_var_unknown_type) => {
                    return Err(Error::from(serde_json::Error::custom(format!(
                        "Received `{local_var_unknown_type}` content type response that cannot be converted to `models::Group`"
                    ))));
                }
            }
        } else {
            let local_var_entity: Option<PutAppApicontrollersCommitteeapiPutcommitteearchiveError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`GroupApi::delete_app_apicontrollers_committeeapi_deletecommittee`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAppApicontrollersCommitteeapiDeletecommitteeError {
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`GroupApi::delete_app_apicontrollers_committeeapi_deletemember`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeleteAppApicontrollersCommitteeapiDeletememberError {
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`GroupApi::get_app_apicontrollers_committeeapi_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAppApicontrollersCommitteeapiGetError {
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`GroupApi::get_app_apicontrollers_committeeapi_getcommittee`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAppApicontrollersCommitteeapiGetcommitteeError {
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`GroupApi::get_app_apicontrollers_committeeapi_getmember`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAppApicontrollersCommitteeapiGetmemberError {
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`GroupApi::get_app_apicontrollers_committeeapi_getmembers`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum GetAppApicontrollersCommitteeapiGetmembersError {
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`GroupApi::post_app_apicontrollers_committeeapi_postcommittee`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostAppApicontrollersCommitteeapiPostcommitteeError {
    Status400(models::PutAppApicontrollersAssociationapiPut400Response),
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`GroupApi::post_app_apicontrollers_committeeapi_postmember`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PostAppApicontrollersCommitteeapiPostmemberError {
    Status400(models::PutAppApicontrollersAssociationapiPut400Response),
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`GroupApi::put_app_apicontrollers_committeeapi_putcommittee`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutAppApicontrollersCommitteeapiPutcommitteeError {
    Status400(models::PutAppApicontrollersAssociationapiPut400Response),
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`GroupApi::put_app_apicontrollers_committeeapi_putcommitteearchive`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PutAppApicontrollersCommitteeapiPutcommitteearchiveError {
    Status400(models::PutAppApicontrollersAssociationapiPut400Response),
    Status500(),
    Status401(),
    UnknownValue(serde_json::Value),
}
