/*
 * Hornet API
 *
 * The Hornet API can be used to programmatically update exposed association data. If you're missing functionality or you experience any problem using the API, you can always contact us.  You will need an API token consisting of a client id and a token value in order to use this API. You can either authenticate using a request header or a query parameter, the choice is yours.  The API is only documented in English.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Association {
    #[serde(rename = "contact_email_address")]
    pub contact_email_address: String,
    /// Saved as string, convert to bytes using SizeConverter.
    #[serde(
        rename = "default_emailbox_size",
        skip_serializing_if = "Option::is_none"
    )]
    pub default_emailbox_size: Option<String>,
    #[serde(
        rename = "detected_storage_size",
        skip_serializing_if = "Option::is_none"
    )]
    pub detected_storage_size: Option<i32>,
    #[serde(rename = "domain")]
    pub domain: String,
    #[serde(rename = "full_name")]
    pub full_name: String,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// Saved as string, convert to bytes using SizeConverter.
    #[serde(rename = "storage_size", skip_serializing_if = "Option::is_none")]
    pub storage_size: Option<String>,
    #[serde(rename = "technical_contact_email_address")]
    pub technical_contact_email_address: String,
    /// Saved as string, convert to bytes using SizeConverter.
    #[serde(rename = "web_email_size", skip_serializing_if = "Option::is_none")]
    pub web_email_size: Option<String>,
}

impl Association {
    pub fn new(
        contact_email_address: String,
        domain: String,
        full_name: String,
        technical_contact_email_address: String,
    ) -> Association {
        Association {
            contact_email_address,
            default_emailbox_size: None,
            detected_storage_size: None,
            domain,
            full_name,
            id: None,
            storage_size: None,
            technical_contact_email_address,
            web_email_size: None,
        }
    }
}
