/*
 * Hornet API
 *
 * The Hornet API can be used to programmatically update exposed association data. If you're missing functionality or you experience any problem using the API, you can always contact us.  You will need an API token consisting of a client id and a token value in order to use this API. You can either authenticate using a request header or a query parameter, the choice is yours.  The API is only documented in English.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssociationMember {
    #[serde(rename = "admin", skip_serializing_if = "Option::is_none")]
    pub admin: Option<bool>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    /// This is equals the internalUsername @ domain
    #[serde(rename = "internal_email", skip_serializing_if = "Option::is_none")]
    pub internal_email: Option<String>,
    #[serde(rename = "internal_username")]
    pub internal_username: String,
    /// Saved as string, convert to bytes using SizeConverter.
    #[serde(rename = "mail_size", skip_serializing_if = "Option::is_none")]
    pub mail_size: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<Box<models::Member>>,
}

impl AssociationMember {
    pub fn new(internal_username: String) -> AssociationMember {
        AssociationMember {
            admin: None,
            id: None,
            internal_email: None,
            internal_username,
            mail_size: None,
            user: None,
        }
    }
}
