/*
 * Hornet API
 *
 * The Hornet API can be used to programmatically update exposed association data. If you're missing functionality or you experience any problem using the API, you can always contact us.  You will need an API token consisting of a client id and a token value in order to use this API. You can either authenticate using a request header or a query parameter, the choice is yours.  The API is only documented in English.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Member {
    #[serde(rename = "email_address", skip_serializing_if = "Option::is_none")]
    pub email_address: Option<String>,
    #[serde(rename = "has_hornet_account", skip_serializing_if = "Option::is_none")]
    pub has_hornet_account: Option<bool>,
    #[serde(rename = "two_factor_enabled", skip_serializing_if = "Option::is_none")]
    pub two_factor_enabled: Option<bool>,
}

impl Member {
    pub fn new() -> Member {
        Member {
            email_address: None,
            has_hornet_account: None,
            two_factor_enabled: None,
        }
    }
}
