/*
 * Hornet API
 *
 * The Hornet API can be used to programmatically update exposed association data. If you're missing functionality or you experience any problem using the API, you can always contact us.  You will need an API token consisting of a client id and a token value in order to use this API. You can either authenticate using a request header or a query parameter, the choice is yours.  The API is only documented in English.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutAppApicontrollersAssociationapiPut400Response {
    /// Message
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Will be absent when the error is not related to field validation
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::PutAppApicontrollersAssociationapiPut400ResponseErrorsInner>>,
}

impl PutAppApicontrollersAssociationapiPut400Response {
    pub fn new() -> PutAppApicontrollersAssociationapiPut400Response {
        PutAppApicontrollersAssociationapiPut400Response {
            message: None,
            errors: None,
        }
    }
}
