/*
 * Hornet API
 *
 * The Hornet API can be used to programmatically update exposed association data. If you're missing functionality or you experience any problem using the API, you can always contact us.  You will need an API token consisting of a client id and a token value in order to use this API. You can either authenticate using a request header or a query parameter, the choice is yours.  The API is only documented in English.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGroupArchive {
    /// By setting this to true, a archive mailbox will be created which will receive all mails sent to this committee.
    #[serde(rename = "archive_enabled", skip_serializing_if = "Option::is_none")]
    pub archive_enabled: Option<bool>,
}

impl UpdateGroupArchive {
    pub fn new() -> UpdateGroupArchive {
        UpdateGroupArchive {
            archive_enabled: None,
        }
    }
}
