/*
 * Hornet API
 *
 * The Hornet API can be used to programmatically update exposed association data. If you're missing functionality or you experience any problem using the API, you can always contact us.  You will need an API token consisting of a client id and a token value in order to use this API. You can either authenticate using a request header or a query parameter, the choice is yours.  The API is only documented in English.
 *
 * The version of the OpenAPI document: 1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAssociationMember {
    #[serde(rename = "admin", skip_serializing_if = "Option::is_none")]
    pub admin: Option<bool>,
    /// You will need to enter a valid storage size here, in the format <number><G/M/K>. For example, use 1G for one gigabyte.
    #[serde(rename = "mail_size", skip_serializing_if = "Option::is_none")]
    pub mail_size: Option<String>,
}

impl UpdateAssociationMember {
    pub fn new() -> UpdateAssociationMember {
        UpdateAssociationMember {
            admin: None,
            mail_size: None,
        }
    }
}
