name: Release

on:
    workflow_dispatch:
        inputs:
            bump:
                description: 'Bump version by semver keyword.'
                required: true
                type: choice
                options:
                    - patch
                    - minor
                    - major

permissions:
    contents: write

jobs:
    release:
        name: Release
        uses: NixySoftware/.github/.github/workflows/release.yml@9704b92a2cefe90342562266d127a0c9dd132640 # v0.2.0
        with:
            bump: ${{ inputs.bump }}
            bump-rust: true
            bump-typescript: false
            extract-version: 'rust'
        secrets:
            app-client-id: ${{ secrets.APP_ID }}
            app-private-key: ${{ secrets.APP_PRIVATE_KEY }}
